### ISSUE TITLE
Higher resolution images for albums (sets) are not downloaded from Flickr

### ISSUE THREAD

**Issue by khladky** [rols1/Kodi-Addon-FlickrExplorer#1]
Higher resolution images for albums (sets) are not downloaded from Flickr, only low res thumbnail images are downloaded and cached. Other options (search etc. etc.) are fine.

**Comment by rols1** [comment]
Thanks, I haven't noticed that yet.  I'm trying to find the error...

**Comment by rols1** [comment]
fixed - V0.7.1 available..
/R
