### ISSUE TITLE
Albums of more than one page not working

### ISSUE THREAD

**Issue by khladky** [rols1/Kodi-Addon-FlickrExplorer#2]
Albums of more than one page are not working.

Page 1 ... etc, dialogue is shown but selecting any page just returns to the single line Return to ... display. Selecting a number of photos larger than the set (100, 500 etc) in Settings and then selecting that set (ie no page select dialogue) works fine.

**Comment by rols1** [comment]
thanks for description - yes, in function BuildPath an api-method for getting photos from photosets was missing (fixed).
I noticed another problem: the flickr-output of "total" does not match the real number of photos (api-method flickr.photosets.getPhotos). So I have to add a correction to display the photos depending on settings.

**Comment by rols1** [comment]
Update V0.7.2 with fixes is available. I've added a deletion function for the photos-cache. You can choose "delete" in cache-Settings and on next menu change the deletion-dialogue will appear.
/R

**Comment by khladky** [comment]
Thanks.

I hate to say this but the low res problem in Albums is back ...

**Comment by rols1** [comment]
grr, and I don't understand this. 'The api-method is correct (key primary_photo_extras with all possible sizes). I need some time ..
/R

**Comment by rols1** [comment]
here is the answer: https://www.flickr.com/help/forum/en-us/72157624141180689/
"Sets are simply links back to the photo's pages. So they only contain thumbnail sized images."
I try to find a easy way to get the original for the list  (maybe  optionally)..
/R

**Comment by khladky** [comment]
https://github.com/lmammino/flickr-set-get
https://github.com/beaufour/flickr-download
etc, .....?

**Comment by rols1** [comment]
thanks but both have the same problem. In a set-list is no direct link back to the original photo.
I think the only way ist to get additional infos for every photo in the list  (api-method flickr.photos.getInfo). The info contains a second secret-term. It seems this can be used for build up the url to the origin-photo.  
I'm not ready but looks good..
/R

**Comment by rols1** [comment]
uff, now it's ok (i hope). Update V0.7.3 is available on Github. 
I've found a better api-call which lists all available sizes for a spezific photo (photos.getSizes). With the info-call sometimes the "originalsecret" was missing.
At this moment only the setting Original is supported. If the sizes-list does'nt contains the mark Original, the addon takes the last source-url - they are ascending sorted.
Would be nice to get a positive feedback..
/R
